### ISSUE TITLE
이 프로젝트가 어떤 의도인지 설명 부탁드려요.

### ISSUE THREAD

**Issue by hohyon-ryu** [open-korean-text/open-korean-text-go#2]
현재 있는 open-korean-text 사전에 단어를 파일로 추가하는 건가요? 그렇게하면 test도 다 깨지고 할텐데요, 테스트 업데이트도 하는 건가요?

**Comment by MechanicKim** [comment]
@nlpenguin 님과 이야기 하였습니다.
이 프로젝트는 go wrapper로 전환하는 것으로 하겠습니다 :-)
